### ISSUE TITLE
pycovjson library

### ISSUE THREAD

**Issue by RileyWilliams** [Reading-eScience-Centre/pycovjson#14]
Currently, pycovjson is structured as a command line utility. Add code to make it easier to use within other projects.

**Comment by RileyWilliams** [comment]
Currently working on this.

**Comment by lewismc** [comment]
Cool, I am very interested in this. In particular a question I have is as follows

> We use Drupal to dynamically generate content for dataset landing pages, based on database tables. We therefore are interested in generating CoverageJSON directly from geospatial database content.

What are the blockers right now to doing this?

**Comment by RileyWilliams** [comment]
Cool, sounds very interesting! I have recently added [convert.py](https://github.com/Reading-eScience-Centre/pycovjson/blob/master/pycovjson/convert.py) which ties together the read and write functions. It still has a few things which need to be added however.

> What are the blockers right now to doing this?

I cannot think of any reason this wouldn't be possible, but will comment if I think of any.
