### ISSUE TITLE
Move into package folder

### ISSUE THREAD

**Issue by letmaik** [Reading-eScience-Centre/pycovjson#2]
All the modules should go into a /pycovjson folder so that when you install the library you can do `import pycovjson`. The command-line script should probably go to /pycovjson/cli.py and be similar to https://github.com/esa/auromat/blob/master/auromat/cli/download.py. (On packaging, the command line scripts are declared in a [setup.py](https://github.com/esa/auromat/blob/master/setup.py#L62) file later on.)

**Comment by lewismc** [comment]
This is done right? @letmaik

**Comment by letmaik** [comment]
Yes, we can do the CLI stuff in another issue.
