### ISSUE TITLE
Add badges for new conda-forge package

### ISSUE THREAD

**Issue by lewismc** [Reading-eScience-Centre/pycovjson#40]
Hi @letmaik @RileyWilliams I wrote a conda-forge recipe for pycovjson, it can be found at https://github.com/conda-forge/pycovjson-feedstock
This issue will simply update the README with correct badges, etc.

**Comment by RileyWilliams** [comment]
This is the first I have heard of conda-forge, looks like a massive improvement over the previous conda build system! 
Edit: Turns out this has been around since 2015, wish I had known about it before

**Comment by lewismc** [comment]
ack @RileyWilliams
