### ISSUE TITLE
pip uninstall fails

### ISSUE THREAD

**Issue by guygriffiths** [Reading-eScience-Centre/pycovjson#9]
After installing with `pip install pycovjson`, I tried to remove it with `pip uninstall pycovjson` and it left at least `pycovjson-convert` and `pycovjson-viewer` still in `/usr/local/bin/`, which had to be removed manually.

**Comment by lewismc** [comment]
This is not an issue for me. Can anyone reproduce?

**Comment by RileyWilliams** [comment]
@guygriffiths Was this with version 0.3.0 of pycovjson using python 3?

**Comment by guygriffiths** [comment]
@RileyWilliams It was using python 3, but I didn't see which version it was - it was whichever would have been picked up by pip on 8/9/16...

**Comment by RileyWilliams** [comment]
I have just tried it and could not reproduce, think this must have been an issue with the 0.3.0 which has now been fixed so will close, feel free to re-open if you find otherwise.
